
---
format:
  html: {toc: true, toc-depth: 4, theme: cosmo, output-file: bin.html}
fontsize: 0.9em
code-block-background: true
include-in-header: {text: '<link rel = "icon" href = "data:," />'}

---
<style></style><style>.printedClojure .sourceCode {
  background-color: transparent;
  border-style: none;
}
</style><style>.clay-limit-image-width .clay-image {max-width: 100%}
</style>
<script src="bin_files/md-default0.js" type="text/javascript"></script><script src="bin_files/md-default1.js" type="text/javascript"></script>
# Welcome to Cashcloj,

My name is Mario Gintili. You can find me on Github [@shellandbull](https://github.com/shellandbull).

Data Science, Data Engineering & Machine Learning have always been a personal interest of mine. During my uni years I was an economics major and I had a deep passion for decision modelling alla [Moneyball](https://en.wikipedia.org/wiki/Moneyball_(film)). My inspiration came from films of the sort

I'm originally a Rubyist and I was introduced to Clojure long time ago. This year(2024, in case you are reading this in the future) I saw a talk @ [London Clojurians](https://londonclojurians.org/) by the [Scicloj](https://scicloj.github.io/) which showcased a new stack for DS/ML. The stack includes:

- Using [spacemacs](https://www.spacemacs.org/), a flavour of emacs, for code editing
- [Interactive programming](https://docs.cider.mx/cider/usage/interactive_programming.html) practises
- [Tablecloth](https://scicloj.github.io/tablecloth/) & [Clay](https://github.com/scicloj/clay) for dataset manipulation & visualisation
- [Quarto](https://quarto.org/) for technical publishing

This site is a documents my journey learning the ML/DS chops

Join me on my silly explorations

## Goals

- Learn to use emacs in evil mode
- Learn data engineering. The usual stuff like feature engineering, scrubbing data, joining datasets, formulating the right questions
- Learn Clojure. My background's in OOP dynamically typed languages, this is my first lisp 
- Learn Scicloj





```{=html}
<div style="background-color:grey;height:2px;width:100%;"></div>
```



```{=html}
<div><pre><small><small>source: src/index.clj</small></small></pre></div>
```
