
---
format:
  html: {toc: true, toc-depth: 4, theme: cosmo, output-file: cashcloj.core.html}
fontsize: 0.9em
code-block-background: true
include-in-header: {text: '<link rel = "icon" href = "data:," />'}

---
<style></style><style>.printedClojure .sourceCode {
  background-color: transparent;
  border-style: none;
}
</style><style>.clay-limit-image-width .clay-image {max-width: 100%}
</style>
<script src="cashcloj.core_files/md-default2.js" type="text/javascript"></script><script src="cashcloj.core_files/md-default3.js" type="text/javascript"></script><script src="cashcloj.core_files/vega4.js" type="text/javascript"></script><script src="cashcloj.core_files/vega5.js" type="text/javascript"></script><script src="cashcloj.core_files/vega6.js" type="text/javascript"></script>

::: {.sourceClojure}
```clojure
(ns cashcloj.core
    (:require [scicloj.clay.v2.api :as clay]
            [clojure.string :as str]
            [tablecloth.api :as tc]
            [tablecloth.column.api :as tcc]
            [scicloj.clay.v2.api :as clay]
            [scicloj.noj.v1.vis.hanami :as hanami]
            [scicloj.kindly.v4.kind :as kind]
            [aerial.hanami.templates :as ht]))
```
:::



::: {.sourceClojure}
```clojure
(kind/md ["
# [Scicloj](https://scicloj.github.io/) explorations part 1 | NASDAQ & Cryptocurrency timeseries

This is my first exploration in the world of data science under the hand of Scicloj.
I decided to give this stack a try due to its [interactive programming](https://docs.cider.mx/cider/usage/interactive_programming.html) capacities.
This concept was introduced to me during a [London Clojurians](https://londonclojurians.org/) talk [\"From data to insights: Clojure for data deep dive\"](https://www.youtube.com/watch?v=eUFf3-og_-Y).

This file you are looking at is rendered using [Clay](https://github.com/scicloj/clay)
"])
```
:::



# [Scicloj](https://scicloj.github.io/) explorations part 1 | NASDAQ & Cryptocurrency timeseries

This is my first exploration in the world of data science under the hand of Scicloj.
I decided to give this stack a try due to its [interactive programming](https://docs.cider.mx/cider/usage/interactive_programming.html) capacities.
This concept was introduced to me during a [London Clojurians](https://londonclojurians.org/) talk ["From data to insights: Clojure for data deep dive"](https://www.youtube.com/watch?v=eUFf3-og_-Y).

This file you are looking at is rendered using [Clay](https://github.com/scicloj/clay)



::: {.sourceClojure}
```clojure
(defn to-kebab-case [s]
  (-> s
    (str/lower-case)
    (str/replace #" " "-")))
```
:::



::: {.sourceClojure}
```clojure
(-> "data/nasdaq-instrument-list.csv"
  (tc/dataset {:key-fn (comp keyword to-kebab-case)})
  (tc/select-columns [:symbol :name]))
```
:::


::: {.clay-dataset}
data/nasdaq-instrument-list.csv [7151 2]:

| :symbol |                                                   :name |
|---------|---------------------------------------------------------|
|       A |                  Agilent Technologies Inc. Common Stock |
|      AA |                          Alcoa Corporation Common Stock |
|    AACG |        ATA Creativity Global American Depositary Shares |
|    AACI |                 Armada Acquisition Corp. I Common Stock |
|   AACIW |                      Armada Acquisition Corp. I Warrant |
|    AACT | Ares Acquisition Corporation II Class A Ordinary Shares |
|    AADI |                       Aadi Bioscience Inc. Common Stock |
|    AAGR |          African Agriculture Holdings Inc. Common Stock |
|   AAGRW |               African Agriculture Holdings Inc. Warrant |
|     AAL |               American Airlines Group Inc. Common Stock |
|     ... |                                                     ... |
|     ZTS |                        Zoetis Inc. Class A Common Stock |
|    ZUMZ |                                Zumiez Inc. Common Stock |
|     ZUO |                         Zuora Inc. Class A Common Stock |
|    ZURA |                Zura Bio Limited Class A Ordinary Shares |
|   ZURAW |                               Zura Bio Limited Warrants |
|    ZVIA |                          Zevia PBC Class A Common Stock |
|    ZVRA |                    Zevra Therapeutics Inc. Common Stock |
|    ZVSA |                  ZyVersa Therapeutics Inc. Common Stock |
|     ZWS |     Zurn Elkay Water Solutions Corporation Common Stock |
|    ZYME |                             Zymeworks Inc. Common Stock |
|    ZYXI |                                 Zynex Inc. Common Stock |


:::



::: {.sourceClojure}
```clojure
(-> "data/nasdaq-instrument-list.csv"
  (tc/dataset {:key-fn (comp keyword to-kebab-case)})
  (tc/order-by :volume)
  (tc/head 10))
```
:::


::: {.clay-dataset}
data/nasdaq-instrument-list.csv [10 11]:

| :symbol |                                                       :name | :last-sale | :net-change | :%-change |    :market-cap |      :country | :ipo-year | :volume |            :sector |                             :industry |
|---------|-------------------------------------------------------------|------------|------------:|-----------|---------------:|---------------|----------:|--------:|--------------------|---------------------------------------|
|   CNFRZ | Conifer Holdings Inc. 9.75% Senior Unsecured Notes due 2028 |     $11.50 |         0.0 |     0.00% | 1.40563132E+08 | United States |           |       1 |                    |                                       |
|    CFFS |               CF Acquisition Corp. VII Class A Common Stock |     $10.84 |         0.0 |     0.00% | 0.00000000E+00 | United States |      2022 |       1 |            Finance |                          Blank Checks |
|   PDYNW |                                  Palladyne AI Corp Warrants |    $0.0505 |         0.0 |     0.00% | 1.30795000E+06 | United States |           |       1 |        Industrials |       Industrial Machinery/Components |
|    KACL |           Kairous Acquisition Corp. Limited Ordinary Shares |     $11.72 |         0.0 |     0.00% | 0.00000000E+00 |      Malaysia |      2022 |       1 |            Finance |                          Blank Checks |
|   AONCW |                      American Oncology Network Inc. Warrant |     $0.265 |         0.0 |     0.00% | 9.46486300E+06 | United States |      2021 |       1 |        Health Care |              Medical/Nursing Services |
|   BBLGW |                                Bone Biologics Corp Warrants |     $23.79 |         0.0 |     0.00% | 1.27095220E+07 | United States |           |       1 |        Health Care |                Industrial Specialties |
|    PMGM |        Priveterra Acquisition Corp. II Class A Common Stock |     $11.09 |         0.0 |     0.00% | 0.00000000E+00 | United States |      2021 |       1 |            Finance |                          Blank Checks |
|   SVREW |                                  SaverOne 2014 Ltd. Warrant |     $0.099 |         0.0 |     0.00% | 6.88834400E+06 |        Israel |      2022 |       1 |         Technology |                          EDP Services |
|   NTRBW |                                      Nutriband Inc. Warrant |      $0.55 |         0.0 |     0.00% | 6.03342900E+06 | United States |           |       1 |        Health Care |                Industrial Specialties |
|     CCZ |                                      Comcast Holdings ZONES |     $54.81 |         0.0 |     0.00% | 2.15053944E+11 | United States |           |       1 | Telecommunications | Cable & Other Pay Television Services |


:::



::: {.sourceClojure}
```clojure
(def nasdaq-instruments
  (-> "data/nasdaq-instrument-list.csv"
      (tc/dataset {:key-fn (comp keyword to-kebab-case)})))
```
:::



::: {.sourceClojure}
```clojure
(-> nasdaq-instruments
  (tc/group-by [:country])
  (tc/aggregate {:count tc/row-count})
  (hanami/plot ht/bar-chart {
                             :X :country
                             :Y :count
                             :XTYPE :nominal
                             :WIDTH 1000
                             :YSCALE {:type "log"}}))
```
:::



```{=html}
<div><script>vegaEmbed(document.currentScript.parentElement, {"encoding":{"y":{"scale":{"type":"log"},"field":"count","type":"quantitative"},"x":{"field":"country","type":"nominal"}},"usermeta":{"embedOptions":{"renderer":"svg"}},"mark":{"type":"bar","tooltip":true},"width":1000,"background":"floralwhite","height":300,"data":{"url":"cashcloj.core_files\/0.csv","format":{"type":"csv"}}});</script></div>
```



::: {.sourceClojure}
```clojure
(-> "data/instruments/1INCH-USD.csv"
    (tc/dataset {:key-fn (comp keyword to-kebab-case)})
    (tc/head 100))
```
:::


::: {.clay-dataset}
data/instruments/1INCH-USD.csv [100 7]:

|      :date | :adj-close |     :close |      :high |       :low |      :open |   :volume |
|------------|-----------:|-----------:|-----------:|-----------:|-----------:|----------:|
| 2023-07-14 | 0.33524400 | 0.33524400 | 0.35731199 | 0.32619700 | 0.34957400 |  22820525 |
| 2023-07-15 | 0.36894101 | 0.36894101 | 0.37873101 | 0.33065999 | 0.33529899 |  79156563 |
| 2023-07-16 | 0.43362901 | 0.43362901 | 0.44532201 | 0.36456200 | 0.36915800 | 231842663 |
| 2023-07-17 | 0.40429100 | 0.40429100 | 0.58109099 | 0.39502901 | 0.43365800 | 776148354 |
| 2023-07-18 | 0.35965601 | 0.35965601 | 0.40430599 | 0.35475701 | 0.40430599 | 123548475 |
| 2023-07-19 | 0.33714199 | 0.33714199 | 0.36555001 | 0.33557901 | 0.35963100 | 100891521 |
| 2023-07-20 | 0.32879999 | 0.32879999 | 0.35777801 | 0.32261801 | 0.33715999 | 101280510 |
| 2023-07-21 | 0.33631900 | 0.33631900 | 0.34398800 | 0.32493699 | 0.32882401 |  65835792 |
| 2023-07-22 | 0.32811299 | 0.32811299 | 0.33769199 | 0.32699901 | 0.33629000 |  32974711 |
| 2023-07-23 | 0.32757801 | 0.32757801 | 0.33134499 | 0.32585999 | 0.32810900 |  33972196 |
| 2023-07-24 | 0.30467799 | 0.30467799 | 0.32782400 | 0.30063599 | 0.32755899 |  55502802 |
| 2023-07-25 | 0.30322000 | 0.30322000 | 0.30656800 | 0.30203000 | 0.30464801 |  23410794 |
| 2023-07-26 | 0.30451700 | 0.30451700 | 0.30798700 | 0.29895300 | 0.30323401 |  22360643 |
| 2023-07-27 | 0.30496600 | 0.30496600 | 0.31217101 | 0.30267999 | 0.30429199 |  20541246 |
| 2023-07-28 | 0.30994099 | 0.30994099 | 0.31081301 | 0.30314800 | 0.30497399 |  17538397 |
| 2023-07-29 | 0.31592199 | 0.31592199 | 0.31593001 | 0.30890799 | 0.30992499 |  18535991 |
| 2023-07-30 | 0.31204200 | 0.31204200 | 0.32242399 | 0.30603200 | 0.31594601 |  30772558 |
| 2023-07-31 | 0.31443501 | 0.31443501 | 0.31774700 | 0.30886900 | 0.31203601 |  22205121 |
| 2023-08-01 | 0.32021600 | 0.32021600 | 0.32021600 | 0.30540401 | 0.31442699 |  28837519 |
| 2023-08-02 | 0.31531399 | 0.31531399 | 0.32085899 | 0.31108800 | 0.32019800 |  24237364 |
| 2023-08-03 | 0.31145999 | 0.31145999 | 0.31951901 | 0.30908599 | 0.31531900 |  22661608 |
| 2023-08-04 | 0.30529001 | 0.30529001 | 0.31415799 | 0.30134001 | 0.31147599 |  24341891 |
| 2023-08-05 | 0.30509901 | 0.30509901 | 0.30538300 | 0.30148900 | 0.30526999 |  14149818 |
| 2023-08-06 | 0.30500999 | 0.30500999 | 0.30977699 | 0.30295101 | 0.30510101 |  28416964 |
| 2023-08-07 | 0.30469501 | 0.30469501 | 0.30887201 | 0.29639801 | 0.30500799 |  29627073 |
| 2023-08-08 | 0.30711100 | 0.30711100 | 0.30869800 | 0.30136999 | 0.30465201 |  15471886 |
| 2023-08-09 | 0.30640101 | 0.30640101 | 0.30848101 | 0.30320400 | 0.30712700 |  15872081 |
| 2023-08-10 | 0.30700901 | 0.30700901 | 0.30900699 | 0.30503300 | 0.30640799 |  12400589 |
| 2023-08-11 | 0.30804399 | 0.30804399 | 0.31000999 | 0.30592099 | 0.30700999 |  12935563 |
| 2023-08-12 | 0.30596799 | 0.30596799 | 0.30890200 | 0.30427200 | 0.30804700 |  12069884 |
| 2023-08-13 | 0.30766600 | 0.30766600 | 0.31170899 | 0.30500299 | 0.30598801 |  14643636 |
| 2023-08-14 | 0.31027400 | 0.31027400 | 0.31305400 | 0.30402499 | 0.30772001 |  18045652 |
| 2023-08-15 | 0.28662100 | 0.28662100 | 0.31053799 | 0.28193501 | 0.31027699 |  31796243 |
| 2023-08-16 | 0.26501599 | 0.26501599 | 0.28684399 | 0.26080000 | 0.28662401 |  26504627 |
| 2023-08-17 | 0.23654100 | 0.23654100 | 0.26984000 | 0.22391599 | 0.26504201 |  36857762 |
| 2023-08-18 | 0.24193700 | 0.24193700 | 0.24440800 | 0.23334201 | 0.23649700 |  23734396 |
| 2023-08-19 | 0.24852701 | 0.24852701 | 0.25015599 | 0.24113899 | 0.24195801 |  14736474 |
| 2023-08-20 | 0.25031900 | 0.25031900 | 0.25112000 | 0.24674299 | 0.24853300 |  12792401 |
| 2023-08-21 | 0.24383800 | 0.24383800 | 0.25051099 | 0.24054500 | 0.25031900 |  17082729 |
| 2023-08-22 | 0.24444801 | 0.24444801 | 0.24635600 | 0.23652899 | 0.24383400 |  16359837 |
| 2023-08-23 | 0.25202301 | 0.25202301 | 0.25417900 | 0.24390200 | 0.24442799 |  16894845 |
| 2023-08-24 | 0.25120899 | 0.25120899 | 0.25396901 | 0.24716800 | 0.25202700 |  14189529 |
| 2023-08-25 | 0.24662200 | 0.24662200 | 0.25128201 | 0.24273100 | 0.25120601 |  14697984 |
| 2023-08-26 | 0.24304500 | 0.24304500 | 0.24903101 | 0.24238800 | 0.24662501 |  13316640 |
| 2023-08-27 | 0.24762100 | 0.24762100 | 0.24762100 | 0.24131800 | 0.24299200 |  12569801 |
| 2023-08-28 | 0.24870700 | 0.24870700 | 0.25290301 | 0.24021700 | 0.24763399 |  16212014 |
| 2023-08-29 | 0.25881201 | 0.25881201 | 0.26231000 | 0.24068500 | 0.24868900 |  22094816 |
| 2023-08-30 | 0.25695500 | 0.25695500 | 0.25915501 | 0.25390899 | 0.25877500 |  17235838 |
| 2023-08-31 | 0.24479400 | 0.24479400 | 0.25696099 | 0.24376599 | 0.25696099 |  17678831 |
| 2023-09-01 | 0.23563001 | 0.23563001 | 0.24623200 | 0.23385499 | 0.24476700 |  19201842 |
| 2023-09-02 | 0.23390999 | 0.23390999 | 0.23601300 | 0.23217399 | 0.23563699 |  15452902 |
| 2023-09-03 | 0.23481099 | 0.23481099 | 0.23627800 | 0.23215400 | 0.23390500 |  15163484 |
| 2023-09-04 | 0.23559099 | 0.23559099 | 0.23861600 | 0.23357600 | 0.23479800 |  12917572 |
| 2023-09-05 | 0.24425399 | 0.24425399 | 0.24439800 | 0.23438700 | 0.23562600 |  17722060 |
| 2023-09-06 | 0.24635901 | 0.24635901 | 0.24894400 | 0.24055800 | 0.24423300 |  18993309 |
| 2023-09-07 | 0.24798501 | 0.24798501 | 0.24830499 | 0.24231000 | 0.24638100 |  14381962 |
| 2023-09-08 | 0.24537100 | 0.24537100 | 0.24841499 | 0.24306500 | 0.24800400 |  11565200 |
| 2023-09-09 | 0.24582300 | 0.24582300 | 0.24743800 | 0.24460600 | 0.24537399 |   9436358 |
| 2023-09-10 | 0.23956500 | 0.23956500 | 0.24584700 | 0.23645701 | 0.24582100 |  15991249 |
| 2023-09-11 | 0.22403800 | 0.22403800 | 0.23983800 | 0.22109801 | 0.23945799 |  20833024 |
| 2023-09-12 | 0.22800100 | 0.22800100 | 0.23469000 | 0.22378699 | 0.22404601 |  16717738 |
| 2023-09-13 | 0.23445700 | 0.23445700 | 0.23572500 | 0.22738700 | 0.22802900 |  13051651 |
| 2023-09-14 | 0.24331900 | 0.24331900 | 0.24456300 | 0.23275600 | 0.23443000 |  14525061 |
| 2023-09-15 | 0.25518799 | 0.25518799 | 0.25577700 | 0.24344000 | 0.24344000 |  19240710 |
| 2023-09-16 | 0.25674400 | 0.25674400 | 0.25970700 | 0.25325599 | 0.25519001 |  15114214 |
| 2023-09-17 | 0.24757800 | 0.24757800 | 0.25674999 | 0.24579100 | 0.25674999 |  11900860 |
| 2023-09-18 | 0.24938300 | 0.24938300 | 0.25601199 | 0.24453300 | 0.24757400 |  14294965 |
| 2023-09-19 | 0.25213000 | 0.25213000 | 0.25529501 | 0.24770001 | 0.24938001 |  14621273 |
| 2023-09-20 | 0.25108600 | 0.25108600 | 0.25264901 | 0.24810900 | 0.25214401 |  14087408 |
| 2023-09-21 | 0.25938401 | 0.25938401 | 0.27789700 | 0.25107601 | 0.25107601 |  80647895 |
| 2023-09-22 | 0.26237300 | 0.26237300 | 0.26344699 | 0.25650200 | 0.25938600 |  21060818 |
| 2023-09-23 | 0.26268801 | 0.26268801 | 0.26784801 | 0.25837901 | 0.26235199 |  14864112 |
| 2023-09-24 | 0.25525799 | 0.25525799 | 0.26295701 | 0.25496799 | 0.26269999 |  11734845 |
| 2023-09-25 | 0.26454699 | 0.26454699 | 0.26470301 | 0.25261301 | 0.25521299 |  19157320 |
| 2023-09-26 | 0.26665199 | 0.26665199 | 0.26962301 | 0.26227501 | 0.26449499 |  15055849 |
| 2023-09-27 | 0.26135901 | 0.26135901 | 0.27174699 | 0.25626701 | 0.26664901 |  20564306 |
| 2023-09-28 | 0.26917699 | 0.26917699 | 0.26948100 | 0.26074800 | 0.26135400 |  18881298 |
| 2023-09-29 | 0.26704800 | 0.26704800 | 0.26944900 | 0.26160699 | 0.26915801 |  16780467 |
| 2023-09-30 | 0.26994801 | 0.26994801 | 0.27118099 | 0.26562700 | 0.26703000 |  13952422 |
| 2023-10-01 | 0.27671501 | 0.27671501 | 0.27876601 | 0.26834801 | 0.26993099 |  16386099 |
| 2023-10-02 | 0.26818299 | 0.26818299 | 0.28086999 | 0.26438999 | 0.27667499 |  25300781 |
| 2023-10-03 | 0.25930399 | 0.25930399 | 0.27009100 | 0.25870001 | 0.26817000 |  14912065 |
| 2023-10-04 | 0.25602400 | 0.25602400 | 0.25935099 | 0.25014099 | 0.25929800 |  11725613 |
| 2023-10-05 | 0.25027201 | 0.25027201 | 0.25663799 | 0.25010100 | 0.25600499 |   9651916 |
| 2023-10-06 | 0.25728199 | 0.25728199 | 0.25780401 | 0.25001001 | 0.25027099 |   8549455 |
| 2023-10-07 | 0.25557101 | 0.25557101 | 0.25827399 | 0.25518799 | 0.25733000 |   8627529 |
| 2023-10-08 | 0.25901401 | 0.25901401 | 0.25918800 | 0.25196600 | 0.25557500 |   9698347 |
| 2023-10-09 | 0.24718800 | 0.24718800 | 0.26075399 | 0.24476799 | 0.25904101 |  15838576 |
| 2023-10-10 | 0.23963700 | 0.23963700 | 0.24716400 | 0.23772199 | 0.24716400 |  20490528 |
| 2023-10-11 | 0.23972100 | 0.23972100 | 0.24094100 | 0.23487900 | 0.23962900 |  12845555 |
| 2023-10-12 | 0.23988600 | 0.23988600 | 0.24086100 | 0.23639700 | 0.23968300 |  11691629 |
| 2023-10-13 | 0.24232399 | 0.24232399 | 0.24514800 | 0.23917800 | 0.23987800 |  22727567 |
| 2023-10-14 | 0.24521500 | 0.24521500 | 0.24776600 | 0.24219000 | 0.24231599 |  11232185 |
| 2023-10-15 | 0.24441101 | 0.24441101 | 0.25009799 | 0.24377300 | 0.24520500 |  11472079 |
| 2023-10-16 | 0.25137901 | 0.25137901 | 0.25520301 | 0.24437700 | 0.24437700 |  19233103 |
| 2023-10-17 | 0.25435400 | 0.25435400 | 0.25482899 | 0.24890301 | 0.25136700 |  20289105 |
| 2023-10-18 | 0.24958099 | 0.24958099 | 0.25573599 | 0.24957199 | 0.25431699 |  18260912 |
| 2023-10-19 | 0.24418300 | 0.24418300 | 0.27486801 | 0.24377701 | 0.24960200 |  86152017 |
| 2023-10-20 | 0.25360301 | 0.25360301 | 0.25499800 | 0.23903801 | 0.24417400 |  26292352 |
| 2023-10-21 | 0.26313001 | 0.26313001 | 0.26715600 | 0.25229001 | 0.25360799 |  16886565 |


:::



::: {.sourceClojure}
```clojure
(-> "data/instruments/1INCH-USD.csv"
  (tc/dataset {:key-fn (comp keyword to-kebab-case)})
  (tc/map-columns :pct-change [:open :close] (fn [open close] (-> close
                                                                  (- open)
                                                                   (* 100))))
  (tc/map-columns :highly-volatile [:pct-change] #(or (tcc/> % 6.0) (tcc/< % -6.0)))
  (hanami/plot ht/point-chart {
                               :X     :date
                               :Y     :pct-change
                               :XTYPE :temporal
                               :WIDTH 1000
                               :COLOR {:field :highly-volatile}
                               }))
```
:::



```{=html}
<div><script>vegaEmbed(document.currentScript.parentElement, {"encoding":{"y":{"field":"pct-change","type":"quantitative"},"color":{"field":"highly-volatile"},"x":{"field":"date","type":"temporal"}},"usermeta":{"embedOptions":{"renderer":"svg"}},"mark":{"type":"circle","tooltip":true},"width":1000,"background":"floralwhite","height":300,"data":{"url":"cashcloj.core_files\/1.csv","format":{"type":"csv"}}});</script></div>
```


TODO
1. Fix scale of the chart. Make the dots coloured if they are above/below 3/-3
2. Add any chart with an interactable slider
3. Tips on staying tidy and organised


```{=html}
<div style="background-color:grey;height:2px;width:100%;"></div>
```



```{=html}
<div><pre><small><small>source: src/cashcloj/core.clj</small></small></pre></div>
```
