
---
format:
  html: {toc: true, toc-depth: 4, theme: cosmo, output-file: index.html}
fontsize: 0.9em
code-block-background: true
include-in-header: {text: '<link rel = "icon" href = "data:," />'}

---
<style></style><style>.printedClojure .sourceCode {
  background-color: transparent;
  border-style: none;
}
</style><style>.clay-limit-image-width .clay-image {max-width: 100%}
</style>
<script src="index_files/md-default0.js" type="text/javascript"></script><script src="index_files/md-default1.js" type="text/javascript"></script>
# Welcome to Cashcloj

Find me on Github [@shellandbull](https://github.com/shellandbull) & on [Linkedin](https://www.linkedin.com/in/mario-gintili-software-engineer/)

Machine learning & data science have always been an interest of mine. Originally an economics major now turned into a software engineer, I had a deep passion for decision modelling. My inspiration for it came from movies like [Moneyball](https://en.wikipedia.org/wiki/Moneyball_(film)) & [A beautiful mind](https://en.wikipedia.org/wiki/A_Beautiful_Mind_(film))

I'm originally a Rubyist, I was introduced to Clojure long time ago, but I never got around using it commercially due to how hard it is to find a Clojure job. This year(2024, in case you are reading this in the future) I saw a talk @ [London Clojurians](https://londonclojurians.org/) by the [Scicloj](https://scicloj.github.io/) which showcased a new stack for DS/ML. The stack includes:

- [Spacemacs](https://www.spacemacs.org/), a flavour of emacs, for code editing
- [Interactive programming](https://docs.cider.mx/cider/usage/interactive_programming.html) practises
- [Tablecloth](https://scicloj.github.io/tablecloth/) & [Clay](https://github.com/scicloj/clay) for dataset manipulation & visualisation
- [Quarto](https://quarto.org/) for technical publishing

This humble Quarto journal you see is a wee attempt at documenting my steps towards achieving prowess at modern, applied ML/DS.

Join me on my silly explorations

## Goals

- Learn emacs in evil mode
- Learn data engineering
- Learn machine learning
- Learn Clojure
- Use the Scicloj stack to achieve all of the above



```{=html}
<div style="background-color:grey;height:2px;width:100%;"></div>
```



```{=html}
<div><pre><small><small>source: src/index.clj</small></small></pre></div>
```
